#ifndef VALIDATION_CONSTANTS_H
#define VALIDATION_CONSTANTS_H

#define MAX_PRIMARY_KEY_ATTRIBUTES 128
#define MAX_RELATIONSHIP_PARTICIPANTS 64
#define MAX_WEAK_ENTITY_REFERENCES 32
#define MAX_INHERITANCE_DEPTH 100

#endif // VALIDATION_CONSTANTS_H
